//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnigmaPuzzle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnigmaPuzzle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunde.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunden.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeile fehlt.
        /// </summary>
        public static string LineMissing {
            get {
                return ResourceManager.GetString("LineMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldung.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuten.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeile hat falsche Länge. Sie muss ein Vielfaches von 2 sein..
        /// </summary>
        public static string MoveLineWrong {
            get {
                return ResourceManager.GetString("MoveLineWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OL.
        /// </summary>
        public static string OL {
            get {
                return ResourceManager.GetString("OL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzliche Gratulation!
        ///
        ///Sie haben das Puzzle in {0} Zügen gelöst..
        /// </summary>
        public static string PuzzleSolved {
            get {
                return ResourceManager.GetString("PuzzleSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie benötigten.
        /// </summary>
        public static string PuzzleSolvedTime {
            get {
                return ResourceManager.GetString("PuzzleSolvedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachfrage.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekunde.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekunden.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher?.
        /// </summary>
        public static string Sure {
            get {
                return ResourceManager.GetString("Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie das laufende Spiel abbrechen?.
        /// </summary>
        public static string SureToCancelGame {
            get {
                return ResourceManager.GetString("SureToCancelGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher? 
        ///
        ///Der Ausdruck wird an den Standarddrucker geschickt..
        /// </summary>
        public static string SureToPrint {
            get {
                return ResourceManager.GetString("SureToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damit wird ein kleiner Dialog gestartet, der ein paar Informationen zum Programm liefert..
        /// </summary>
        public static string TipAbout {
            get {
                return ResourceManager.GetString("TipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damit beenden Sie das Programm..
        /// </summary>
        public static string TipClose {
            get {
                return ResourceManager.GetString("TipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falls Ihnen die voreingestellten Farben nicht gefallen, dann können Sie in der Tabelle die Farben ändern. 
        ///Achten Sie bitte darauf, dass die Farben gut unterscheidbar sind. 
        ///
        ///Sie können die Farben ändern indem Sie auf die farbigen Balken klicken und eine
        ///neue Farbe im Farbauswahldialog wählen..
        /// </summary>
        public static string TipCols {
            get {
                return ResourceManager.GetString("TipCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Klick auf diesen Schalter startet den Konfigurationsdialog..
        /// </summary>
        public static string TipConfig {
            get {
                return ResourceManager.GetString("TipConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier finden Sie die Anleitung zum Programm. 
        ///Es wird die Anleitung als PDF-Dokument angezeigt. Das geht natürlich nur, 
        ///wenn auf dem Rechner ein PDF-Viewer installiert ist..
        /// </summary>
        public static string TipHelp {
            get {
                return ResourceManager.GetString("TipHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der aktuell gewählte Level..
        /// </summary>
        public static string TipLevel {
            get {
                return ResourceManager.GetString("TipLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damit reduzieren Sie den Schwierigkeitsgrad der Spielfläche. 
        ///Die Spielfläche wird in die Grundstellung des Levels gebracht..
        /// </summary>
        public static string TipLevelDown {
            get {
                return ResourceManager.GetString("TipLevelDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damit erhöhen Sie den Schwierigkeitsgrad der Spielfläche. 
        ///Die Spielfläche wird in die Grundstellung des Levels gebracht..
        /// </summary>
        public static string TipLevelUp {
            get {
                return ResourceManager.GetString("TipLevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damit starten Sie ein neues Spiel. Die Scheiben werden zufällig 
        ///ein paar Mal gedreht. 
        ///
        ///Wie oft die Scheiben gedreht werden und ob die Drehungen angezeigt 
        ///werden, können Sie im Konfig-Dialog einstellen..
        /// </summary>
        public static string TipNew {
            get {
                return ResourceManager.GetString("TipNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Zahl legt fest, wie oft bei einem neuen Spiel die Scheiben zufällig 
        ///durch den Computer gedreht werden. Je grösser die Zahl desto grösser 
        ///das Durcheinander und desto schwieriger ist es den Originalzustand wieder herzustellen..
        /// </summary>
        public static string TipNumTurns {
            get {
                return ResourceManager.GetString("TipNumTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damit lässt sich ein gespeichertes Spiel wieder herstellen. 
        ///Sie erhalten einen Datei öffnen Dialog in dem Sie die Datei 
        ///mit dem gespeicherten Spiel auswählen können..
        /// </summary>
        public static string TipOpen {
            get {
                return ResourceManager.GetString("TipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Originallayout des Levels..
        /// </summary>
        public static string TipPicOriginal {
            get {
                return ResourceManager.GetString("TipPicOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit diesem Schalter können Sie die Spielfläche ausdrucken. 
        ///Es wird nur die eigentliche Spielfläche auf eine A4-Blatt gedruckt. 
        ///
        ///Der Druck erfolgt nach einer Nachfrage auf dem Standarddrucker..
        /// </summary>
        public static string TipPrint {
            get {
                return ResourceManager.GetString("TipPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bringt die Spielfläche wieder in den Originalzustand des aktuellen Spiellevels. 
        ///Ein laufendes Spiel wird abgebrochen..
        /// </summary>
        public static string TipReset {
            get {
                return ResourceManager.GetString("TipReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ist die Verzögerung in Millisekunden, die zwischen den Teilschritten gewartet wird..
        /// </summary>
        public static string TipRotationDelay {
            get {
                return ResourceManager.GetString("TipRotationDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Zahl gibt an, wie viele Teilbilder gezeichnet werden, 
        ///wenn eine Scheibe um 60 Grad gedreht wird. Der Wert vier legt 
        ///also fest, dass für alle 15 Grad ein neues Bild angezeigt wird. 
        ///Zwischen den Bildern wird so lange gewartet, wie unter 
        ///Rotationsverzögerung festgelegt wurde.
        ///Je mehr Teilschritte gezeigt werden desto geschmeidiger sieht die 
        ///Drehbewegung aus. Es benötigt aber auch viele Systemressourcen..
        /// </summary>
        public static string TipRotationSteps {
            get {
                return ResourceManager.GetString("TipRotationSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Funktion erlaubt es, den aktuellen Stand eines Spiels zu speichern, 
        ///damit Sie später weiter spielen können. Sie erhalten einen Speichern unter Dialog 
        ///und können einen Dateinamen für den aktuellen Spielstand festlegen. 
        ///Der Dateityp muss auf Enigma eingestellt sein.
        ///
        ///Sie können aber auch nur das Bild als JPEG-Datei speichern. 
        ///Dazu wählen Sie im Speichern unter Dialog den entsprechenden Dateityp (Image)..
        /// </summary>
        public static string TipSave {
            get {
                return ResourceManager.GetString("TipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie können sich die Dreher bei einem neuen Spiel zeigen lassen. 
        ///Wenn Sie hier den Haken entfernen, dann wir bei einem neuen 
        ///Spiel ganz einfach das Ergebnis von zufälligen Drehern angezeigt. 
        ///Andernfalls sehen Sie jede Drehbewegung..
        /// </summary>
        public static string TipShowTurns {
            get {
                return ResourceManager.GetString("TipShowTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn diese Checkbox aktiviert ist, ertönt beim Drehen einer Scheibe ein Geräusch..
        /// </summary>
        public static string TipSound {
            get {
                return ResourceManager.GetString("TipSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie können damit das Überschwingen ein- oder ausschalten..
        /// </summary>
        public static string TipSwing {
            get {
                return ResourceManager.GetString("TipSwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Wert legt fest, wie heftig das Überschwingen beim Drehen 
        ///erfolgen soll. Je grösser der Wert desto länger dauert eine Drehbewegung.
        ///Das ist eine Spielerei, welche die Drehbewegung noch realistischer erscheinen lassen soll..
        /// </summary>
        public static string TipSwingSteps {
            get {
                return ResourceManager.GetString("TipSwingSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfernen Sie den Haken, wenn Sie keine Tooltips auf Schaltern und Eingabefeldern mehr sehen möchten..
        /// </summary>
        public static string TipToolTips {
            get {
                return ResourceManager.GetString("TipToolTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UL.
        /// </summary>
        public static string UL {
            get {
                return ResourceManager.GetString("UL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UR.
        /// </summary>
        public static string UR {
            get {
                return ResourceManager.GetString("UR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
